# Generated by Django 4.0.4 on 2022-07-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=45)),
                ('Subcategoria', models.CharField(blank=True, max_length=750, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Apellido', models.CharField(max_length=15)),
                ('Cedula', models.CharField(max_length=11)),
                ('Direccion', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('Telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('Celular', models.CharField(max_length=10, verbose_name='Telefono Movil')),
                ('Patrocinador', models.CharField(blank=True, max_length=240, null=True)),
                ('LugarNacimiento', models.CharField(max_length=240, verbose_name='Lugar De Nacimiento')),
                ('FechaNacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha De Nacimiento')),
                ('edad', models.CharField(blank=True, max_length=3)),
                ('Hijos', models.CharField(max_length=1)),
                ('hijas', models.CharField(max_length=1)),
                ('EstadoCivil', models.CharField(max_length=40, verbose_name='Estado Civil')),
                ('LugarTrabajo', models.CharField(max_length=100, verbose_name='Empresa para La que Trabaja')),
                ('TelTrabajo', models.CharField(max_length=10, verbose_name=' Telefono De Lugar De trabajo')),
                ('DireccionTrabajo', models.CharField(max_length=240, verbose_name='Direccion De  Lugar De Trabajo')),
                ('solicitud', models.FileField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Estado', models.CharField(default='ninguno', max_length=240, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('Correo', models.EmailField(max_length=45, verbose_name='Correo Electronico')),
                ('Telefono', models.CharField(max_length=11, verbose_name='Telefono')),
                ('Asunto', models.CharField(max_length=75, verbose_name='Asunto')),
                ('Mensaje', models.TextField(default='', max_length=340, verbose_name='Mensaje')),
                ('Estado', models.CharField(default='Pendiente', max_length=240, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=45)),
                ('Apellido', models.CharField(max_length=40)),
                ('Role', models.CharField(max_length=45)),
                ('HistorialProfesional', models.TextField(max_length=750, verbose_name='Historial Profesional')),
                ('FotoPerfil', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=15)),
                ('descripcion', models.TextField(default='', max_length=340)),
                ('ImpactoSocial', models.CharField(max_length=240, verbose_name='Impacto Social')),
                ('IMpactoMedioAmbiental', models.CharField(blank=True, max_length=240, null=True, verbose_name='Impacto Medio Ambiental')),
                ('CapitalInvertido', models.CharField(default='', max_length=10, verbose_name='Capital Invertido')),
                ('Duracion', models.CharField(default='ninguno', max_length=240, verbose_name='Duracion')),
                ('Imagen1', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Imagen2', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Imagen3', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Imagen4', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=15)),
                ('Portada', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('descripcion', models.TextField(default='', max_length=340)),
                ('ImpactoEconomico', models.CharField(default='ninguno', max_length=240, verbose_name='Impacto Economico')),
                ('ImpactoSocial', models.CharField(max_length=240, verbose_name='Impacto Social')),
                ('IMpactoMedioAmbiental', models.CharField(blank=True, max_length=240, null=True, verbose_name='Impacto Medio Ambiental')),
                ('CapitalInvertido', models.CharField(default='', max_length=10, verbose_name='Capital Invertido')),
                ('TiempoEjecucion', models.CharField(blank=True, max_length=240, null=True, verbose_name='Tiempo De Ejecucion')),
                ('Duracion', models.CharField(default='ninguno', max_length=240, verbose_name='Duracion')),
                ('Imagen1', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Imagen2', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Imagen3', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Imagen4', models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
            ],
        ),
        migrations.CreateModel(
            name='SociosJuridicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreINS', models.CharField(max_length=40)),
                ('TipoOrganizacion', models.CharField(max_length=40)),
                ('RNC', models.CharField(max_length=11)),
                ('Direccion', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('Telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('Celular', models.CharField(max_length=10, verbose_name='Telefono Movil')),
                ('WebSite', models.CharField(blank=True, max_length=240, null=True)),
                ('PagoRealizado', models.CharField(max_length=240, verbose_name='Pago Realizado')),
                ('solicitud', models.FileField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\Kevin\\Documents\\fakedrive\\OneDrive\\CoopresolWeb\\solicitudes')),
                ('Estado', models.CharField(default='ninguno', max_length=240, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=45)),
                ('VideoURL', models.CharField(max_length=250)),
                ('Categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inicio.categoria')),
            ],
        ),
    ]
