# Generated by Django 4.0.6 on 2022-08-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='Celular',
            field=models.CharField(max_length=10, verbose_name='Teléfono Móvil'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='DireccionTrabajo',
            field=models.CharField(max_length=240, verbose_name='Dirección De Lugar De Trabajo'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='TelTrabajo',
            field=models.CharField(max_length=10, verbose_name=' Teléfono De Lugar De trabajo'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='contactos',
            name='solicitud',
            field=models.FileField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='Correo',
            field=models.EmailField(max_length=45, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='correo',
            name='Telefono',
            field=models.CharField(max_length=11, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='FotoPerfil',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='IMpactoMedioAmbiental',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Impacto medioambiental'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Imagen1',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Imagen2',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Imagen3',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='Imagen4',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='IMpactoMedioAmbiental',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Impacto medioambiental'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Imagen1',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Imagen2',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Imagen3',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Imagen4',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='ImpactoEconomico',
            field=models.CharField(default='ninguno', max_length=240, verbose_name='Impacto Económico'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='Portada',
            field=models.ImageField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
        migrations.AlterField(
            model_name='sociosjuridicos',
            name='Celular',
            field=models.CharField(max_length=10, verbose_name='Teléfono Móvil'),
        ),
        migrations.AlterField(
            model_name='sociosjuridicos',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='sociosjuridicos',
            name='solicitud',
            field=models.FileField(default='tierra.jpg', max_length=240, null=True, upload_to='C:\\Users\\NEWMAN SENA\\Desktop\\para probar\\Actualizado\\solicitudes'),
        ),
    ]
